set serveroutput on;

DECLARE

VEDAD votantes.FECHANACIMIENTO%TYPE;
JEDAD votantes.FECHANACIMIENTO%TYPE;

BEGIN
SELECT FECHANACIMIENTO INTO VEDAD FROM votantes WHERE fechanacimiento = (SELECT MIN(fechanacimiento) FROM votantes);
SELECT FECHANACIMIENTO INTO JEDAD FROM votantes WHERE fechanacimiento = (SELECT MAX(fechanacimiento) FROM votantes);
DBMS_OUTPUT.PUT_LINE(VEDAD);
DBMS_OUTPUT.PUT_LINE(JEDAD);
DBMS_OUTPUT.PUT_LINE(ceil((JEDAD - VEDAD) / 365.25));
END;