DROP TABLE consultas CASCADE CONSTRAINTS;
DROP TABLE consultas_datos CASCADE CONSTRAINTS;
DROP TABLE eventos CASCADE CONSTRAINTS;
DROP TABLE eventos_resultados CASCADE CONSTRAINTS;
DROP TABLE localidades CASCADE CONSTRAINTS;
DROP TABLE partidos CASCADE CONSTRAINTS;
DROP TABLE provincias CASCADE CONSTRAINTS;
DROP TABLE votantes CASCADE CONSTRAINTS;